version: '3.9'
services:
  app:
    build: ./infra/node
    ports:
      - '8080:8080'
    volumes:
      - ./:/src
    stdin_open: true
    tty: true

  ng:
    build: ./infra/ng
    ports:
      - '4200:4200'
    volumes:
      - './server:/src'
    tty: true

  rx:
    build: ./infra/rx
    ports:
      - '4201:4201'
    volumes:
      - './server:/src'
    tty: true
